import '../models/shipping_request.dart';
import '../models/enums.dart';
import '../services/affiliate_api_service.dart';

/// Affiliate Shipment Repository
///
/// Uses Firestore directly via AffiliateService
const bool _useMockShipmentData = false;

class AffiliateShipmentRepository {
  final AffiliateService _affiliateService;

  AffiliateShipmentRepository({AffiliateService? affiliateService})
      : _affiliateService = affiliateService ?? AffiliateService();

  /// Get all affiliate shipments from Firestore
  Stream<List<ShippingRequest>> getShipments({ShippingStatus? statusFilter}) {
    if (_useMockShipmentData) {
      final allShipments = _getMockShipments();
      final filtered = statusFilter == null
          ? allShipments
          : allShipments.where((s) => s.status == statusFilter).toList();
      return Stream.value(filtered);
    }

    // Real Firestore data via AffiliateService
    return _affiliateService.watchShipments(status: statusFilter);
  }

  /// Get shipment by ID
  Future<ShippingRequest?> getShipment(String shipmentId) async {
    if (_useMockShipmentData) {
      return _getMockShipments().firstWhere(
        (shipment) => shipment.id == shipmentId,
        orElse: () => throw Exception('Shipment not found'),
      );
    }

    return null;
  }

  /// Get shipment statistics
  Map<String, int> getShipmentStats(List<ShippingRequest> shipments) {
    return {
      'total': shipments.length,
      'pending':
          shipments.where((s) => s.status == ShippingStatus.pending).length,
      'inTransit':
          shipments.where((s) => s.status == ShippingStatus.inTransit).length,
      'delivered':
          shipments.where((s) => s.status == ShippingStatus.delivered).length,
    };
  }

  /// Search shipments
  List<ShippingRequest> searchShipments(
      List<ShippingRequest> shipments, String query) {
    if (query.isEmpty) return shipments;

    final lowerQuery = query.toLowerCase();
    return shipments.where((shipment) {
      return shipment.id.toLowerCase().contains(lowerQuery) ||
          (shipment.clientName?.toLowerCase().contains(lowerQuery) ?? false) ||
          (shipment.trackingNumber?.toLowerCase().contains(lowerQuery) ??
              false);
    }).toList();
  }

  /// Mock shipments - 15 shipments with various statuses
  List<ShippingRequest> _getMockShipments() {
    final now = DateTime.now();

    return [
      // Delivered (5)
      ShippingRequest(
        id: 'SHIP-2025-001',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Alice Johnson',
        clientEmail: 'alice.j@example.com',
        clientPhone: '+1-555-0201',
        type: ShippingType.air,
        status: ShippingStatus.delivered,
        priority: ShippingPriority.express,
        origin: 'Lagos, Nigeria',
        destination: 'Abuja, Nigeria',
        weight: 5.5,
        length: 30,
        width: 20,
        height: 15,
        description: 'Sports equipment - Soccer balls (2 pcs)',
        estimatedCost: 2500.00,
        actualCost: 2500.00,
        trackingNumber: 'TRK-001-ABC',
        carrier: 'DHL Express',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now.subtract(const Duration(days: 8)),
        estimatedDelivery: now.subtract(const Duration(days: 10)),
        actualDelivery: now.subtract(const Duration(days: 8)),
        affiliateCommission: 375.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-002',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Bob Williams',
        clientEmail: 'bob.w@example.com',
        clientPhone: '+1-555-0202',
        type: ShippingType.air,
        status: ShippingStatus.delivered,
        priority: ShippingPriority.standard,
        origin: 'Port Harcourt, Nigeria',
        destination: 'Kano, Nigeria',
        weight: 3.2,
        length: 25,
        width: 15,
        height: 10,
        description: 'Athletic shoes and accessories',
        estimatedCost: 1800.00,
        actualCost: 1800.00,
        trackingNumber: 'TRK-002-DEF',
        carrier: 'FedEx',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 12)),
        estimatedDelivery: now.subtract(const Duration(days: 15)),
        actualDelivery: now.subtract(const Duration(days: 12)),
        affiliateCommission: 270.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-003',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Carol Martinez',
        clientEmail: 'carol.m@example.com',
        clientPhone: '+1-555-0203',
        type: ShippingType.air,
        status: ShippingStatus.delivered,
        priority: ShippingPriority.standard,
        origin: 'Ibadan, Nigeria',
        destination: 'Benin City, Nigeria',
        weight: 8.0,
        length: 40,
        width: 30,
        height: 25,
        description: 'Basketball hoops and equipment',
        estimatedCost: 3200.00,
        actualCost: 3200.00,
        trackingNumber: 'TRK-003-GHI',
        carrier: 'UPS',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 18)),
        estimatedDelivery: now.subtract(const Duration(days: 20)),
        actualDelivery: now.subtract(const Duration(days: 18)),
        affiliateCommission: 480.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-004',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'David Lee',
        clientEmail: 'david.l@example.com',
        clientPhone: '+1-555-0204',
        type: ShippingType.sea,
        status: ShippingStatus.delivered,
        priority: ShippingPriority.express,
        origin: 'Lagos, Nigeria',
        destination: 'Accra, Ghana',
        weight: 12.5,
        length: 50,
        width: 40,
        height: 35,
        description: 'Fitness equipment - weights and bars',
        estimatedCost: 5500.00,
        actualCost: 5500.00,
        trackingNumber: 'TRK-004-JKL',
        carrier: 'DHL Express',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 20)),
        estimatedDelivery: now.subtract(const Duration(days: 25)),
        actualDelivery: now.subtract(const Duration(days: 20)),
        affiliateCommission: 825.00,
        requiresCustomsClearance: true,
      ),
      ShippingRequest(
        id: 'SHIP-2025-005',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Emma Brown',
        clientEmail: 'emma.b@example.com',
        clientPhone: '+1-555-0205',
        type: ShippingType.air,
        status: ShippingStatus.delivered,
        priority: ShippingPriority.standard,
        origin: 'Enugu, Nigeria',
        destination: 'Calabar, Nigeria',
        weight: 4.5,
        length: 28,
        width: 18,
        height: 12,
        description: 'Tennis rackets and balls',
        estimatedCost: 2100.00,
        actualCost: 2100.00,
        trackingNumber: 'TRK-005-MNO',
        carrier: 'FedEx',
        createdAt: now.subtract(const Duration(days: 35)),
        updatedAt: now.subtract(const Duration(days: 28)),
        estimatedDelivery: now.subtract(const Duration(days: 30)),
        actualDelivery: now.subtract(const Duration(days: 28)),
        affiliateCommission: 315.00,
      ),

      // In Transit (6)
      ShippingRequest(
        id: 'SHIP-2025-006',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Frank Garcia',
        clientEmail: 'frank.g@example.com',
        clientPhone: '+1-555-0206',
        type: ShippingType.air,
        status: ShippingStatus.inTransit,
        priority: ShippingPriority.express,
        origin: 'Lagos, Nigeria',
        destination: 'Jos, Nigeria',
        weight: 6.8,
        length: 35,
        width: 25,
        height: 20,
        description: 'Cycling equipment and helmets',
        estimatedCost: 2800.00,
        actualCost: 2800.00,
        trackingNumber: 'TRK-006-PQR',
        carrier: 'DHL Express',
        createdAt: now.subtract(const Duration(days: 3)),
        updatedAt: now.subtract(const Duration(hours: 12)),
        estimatedDelivery: now.add(const Duration(days: 2)),
        affiliateCommission: 420.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-007',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Grace Taylor',
        clientEmail: 'grace.t@example.com',
        clientPhone: '+1-555-0207',
        type: ShippingType.air,
        status: ShippingStatus.inTransit,
        priority: ShippingPriority.standard,
        origin: 'Abuja, Nigeria',
        destination: 'Warri, Nigeria',
        weight: 5.2,
        length: 32,
        width: 22,
        height: 18,
        description: 'Swimming gear and goggles',
        estimatedCost: 2300.00,
        actualCost: 2300.00,
        trackingNumber: 'TRK-007-STU',
        carrier: 'UPS',
        createdAt: now.subtract(const Duration(days: 4)),
        updatedAt: now.subtract(const Duration(days: 1)),
        estimatedDelivery: now.add(const Duration(days: 3)),
        affiliateCommission: 345.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-008',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Henry Anderson',
        clientEmail: 'henry.a@example.com',
        clientPhone: '+1-555-0208',
        type: ShippingType.sea,
        status: ShippingStatus.inTransit,
        priority: ShippingPriority.express,
        origin: 'Lagos, Nigeria',
        destination: 'Nairobi, Kenya',
        weight: 15.0,
        length: 55,
        width: 45,
        height: 40,
        description: 'Golf equipment - clubs and bags',
        estimatedCost: 6200.00,
        actualCost: 6200.00,
        trackingNumber: 'TRK-008-VWX',
        carrier: 'DHL Express',
        createdAt: now.subtract(const Duration(days: 5)),
        updatedAt: now.subtract(const Duration(days: 2)),
        estimatedDelivery: now.add(const Duration(days: 4)),
        affiliateCommission: 930.00,
        requiresCustomsClearance: true,
      ),
      ShippingRequest(
        id: 'SHIP-2025-009',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Isabel White',
        clientEmail: 'isabel.w@example.com',
        clientPhone: '+1-555-0209',
        type: ShippingType.air,
        status: ShippingStatus.inTransit,
        priority: ShippingPriority.standard,
        origin: 'Kano, Nigeria',
        destination: 'Sokoto, Nigeria',
        weight: 3.8,
        length: 26,
        width: 16,
        height: 11,
        description: 'Running accessories and water bottles',
        estimatedCost: 1900.00,
        actualCost: 1900.00,
        trackingNumber: 'TRK-009-YZA',
        carrier: 'FedEx',
        createdAt: now.subtract(const Duration(days: 2)),
        updatedAt: now.subtract(const Duration(hours: 8)),
        estimatedDelivery: now.add(const Duration(days: 5)),
        affiliateCommission: 285.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-010',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Jack Robinson',
        clientEmail: 'jack.r@example.com',
        clientPhone: '+1-555-0210',
        type: ShippingType.air,
        status: ShippingStatus.inTransit,
        priority: ShippingPriority.express,
        origin: 'Port Harcourt, Nigeria',
        destination: 'Uyo, Nigeria',
        weight: 7.5,
        length: 38,
        width: 28,
        height: 22,
        description: 'Boxing gloves and training equipment',
        estimatedCost: 3100.00,
        actualCost: 3100.00,
        trackingNumber: 'TRK-010-BCD',
        carrier: 'DHL Express',
        createdAt: now.subtract(const Duration(days: 1)),
        updatedAt: now.subtract(const Duration(hours: 4)),
        estimatedDelivery: now.add(const Duration(days: 3)),
        affiliateCommission: 465.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-011',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Karen Davis',
        clientEmail: 'karen.d@example.com',
        clientPhone: '+1-555-0211',
        type: ShippingType.air,
        status: ShippingStatus.inTransit,
        priority: ShippingPriority.standard,
        origin: 'Ibadan, Nigeria',
        destination: 'Akure, Nigeria',
        weight: 4.2,
        length: 29,
        width: 19,
        height: 14,
        description: 'Yoga mats and blocks',
        estimatedCost: 2000.00,
        actualCost: 2000.00,
        trackingNumber: 'TRK-011-EFG',
        carrier: 'UPS',
        createdAt: now.subtract(const Duration(hours: 18)),
        updatedAt: now.subtract(const Duration(hours: 2)),
        estimatedDelivery: now.add(const Duration(days: 6)),
        affiliateCommission: 300.00,
      ),

      // Pending (4)
      ShippingRequest(
        id: 'SHIP-2025-012',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Leo Martinez',
        clientEmail: 'leo.m@example.com',
        clientPhone: '+1-555-0212',
        type: ShippingType.air,
        status: ShippingStatus.pending,
        priority: ShippingPriority.express,
        origin: 'Lagos, Nigeria',
        destination: 'Owerri, Nigeria',
        weight: 9.0,
        length: 42,
        width: 32,
        height: 28,
        description: 'Table tennis tables and paddles',
        estimatedCost: 3800.00,
        actualCost: 0.00,
        createdAt: now.subtract(const Duration(hours: 3)),
        estimatedDelivery: now.add(const Duration(days: 5)),
        affiliateCommission: 570.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-013',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Maria Wilson',
        clientEmail: 'maria.w@example.com',
        clientPhone: '+1-555-0213',
        type: ShippingType.air,
        status: ShippingStatus.pending,
        priority: ShippingPriority.standard,
        origin: 'Abuja, Nigeria',
        destination: 'Minna, Nigeria',
        weight: 5.5,
        length: 31,
        width: 21,
        height: 16,
        description: 'Badminton rackets and shuttlecocks',
        estimatedCost: 2400.00,
        actualCost: 0.00,
        createdAt: now.subtract(const Duration(hours: 6)),
        estimatedDelivery: now.add(const Duration(days: 7)),
        affiliateCommission: 360.00,
      ),
      ShippingRequest(
        id: 'SHIP-2025-014',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Nathan Clark',
        clientEmail: 'nathan.c@example.com',
        clientPhone: '+1-555-0214',
        type: ShippingType.sea,
        status: ShippingStatus.pending,
        priority: ShippingPriority.express,
        origin: 'Lagos, Nigeria',
        destination: 'Johannesburg, South Africa',
        weight: 18.0,
        length: 60,
        width: 50,
        height: 45,
        description: 'Rugby equipment and training gear',
        estimatedCost: 7500.00,
        actualCost: 0.00,
        createdAt: now.subtract(const Duration(hours: 12)),
        estimatedDelivery: now.add(const Duration(days: 8)),
        affiliateCommission: 1125.00,
        requiresCustomsClearance: true,
        requiresInsurance: true,
      ),
      ShippingRequest(
        id: 'SHIP-2025-015',
        requesterId: 'affiliate_001',
        affiliateId: 'AFF-001',
        clientName: 'Olivia Thomas',
        clientEmail: 'olivia.t@example.com',
        clientPhone: '+1-555-0215',
        type: ShippingType.air,
        status: ShippingStatus.pending,
        priority: ShippingPriority.standard,
        origin: 'Enugu, Nigeria',
        destination: 'Nsukka, Nigeria',
        weight: 3.5,
        length: 27,
        width: 17,
        height: 13,
        description: 'Cricket bats and balls',
        estimatedCost: 1950.00,
        actualCost: 0.00,
        createdAt: now.subtract(const Duration(hours: 1)),
        estimatedDelivery: now.add(const Duration(days: 6)),
        affiliateCommission: 292.50,
      ),
    ];
  }
}
