import 'package:cloud_firestore/cloud_firestore.dart';

/// Simplified Shipping Request Model - Firebase/Firestore Only
/// No PostgreSQL, direct to Firestore
class SimpleShippingRequest {
  final String id;
  final String? affiliateId; // Optional - for affiliate referrals
  final String? userId; // Optional - for registered users
  final String guestEmail; // Email for unregistered users (for notifications)

  // Freight Type
  final String freightType; // "air" or "sea" (legacy values may still appear)

  // Shipment Details
  final String itemDescription;
  final String departingLocation; // origin address
  final String priority; // regular or express
  final String destinationLocation; // destination address
  final double shipmentWeightKg;
  final String shipmentDimensions; // e.g., "100x50x30"
  final String shipmentPackaging;

  // Sender Details
  final String senderName;
  final String senderAddress;
  final String senderPhone;
  final String senderEmail;

  // Receiver Details
  final String receiverName;
  final String receiverAddress;
  final String receiverPhone;
  final String receiverEmail;

  // Additional
  final List<String>? attachmentUrls; // Firestore storage URLs
  final String? otherInformation;

  // Metadata
  final DateTime createdAt;
  final String status; // "pending", "approved", "in-transit", "delivered"
  final String? adminNotes;

  // request category: guest, customer, or affiliate
  final String category;

  SimpleShippingRequest({
    required this.id,
    this.affiliateId,
    this.userId,
    required this.guestEmail,
    required this.freightType,
    required this.itemDescription,
    required this.departingLocation,
    this.priority = 'regular',
    required this.destinationLocation,
    required this.shipmentWeightKg,
    required this.shipmentDimensions,
    required this.shipmentPackaging,
    required this.senderName,
    required this.senderAddress,
    required this.senderPhone,
    required this.senderEmail,
    required this.receiverName,
    required this.receiverAddress,
    required this.receiverPhone,
    required this.receiverEmail,
    this.attachmentUrls,
    this.otherInformation,
    required this.createdAt,
    this.status = 'pending',
    this.adminNotes,
    required this.category,
  });

  /// Convert to Firestore JSON
  /// Maps model fields to Firestore collection structure for security rules compliance
  Map<String, dynamic> toFirestore() {
    // Parse dimensions from string "100x50x30" to separate fields
    List<String> dims = shipmentDimensions.split('x');
    double length =
        double.tryParse(dims.isNotEmpty ? dims[0].trim() : '0') ?? 0;
    double width = double.tryParse(dims.length > 1 ? dims[1].trim() : '0') ?? 0;
    double height =
        double.tryParse(dims.length > 2 ? dims[2].trim() : '0') ?? 0;

    return {
      // PRIMARY KEYS & IDENTIFIERS
      'requesterId': userId ??
          'guest_${senderEmail.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')}',
      'id': id,
      // CUSTOMER INFO (mapped to Firestore rules expectations)
      'clientName': senderName,
      'clientEmail': guestEmail.isEmpty ? senderEmail : guestEmail,
      'clientPhone': senderPhone,

      // SHIPMENT DETAILS (mapped to Firestore rules expectations)
      'type': freightType,
      'origin': departingLocation,
      'priority': priority,
      'destination': destinationLocation,
      'description': itemDescription,
      'weight': shipmentWeightKg,
      'length': length,
      'width': width,
      'height': height,
      'packagingType': shipmentPackaging,

      // SENDER/RECEIVER DETAILED INFO
      'senderName': senderName,
      'senderAddress': senderAddress,
      'senderPhone': senderPhone,
      'senderEmail': senderEmail,
      'receiverName': receiverName,
      'receiverAddress': receiverAddress,
      'receiverPhone': receiverPhone,
      'receiverEmail': receiverEmail,

      // ADDITIONAL INFO
      'attachmentUrls': attachmentUrls ?? [],
      'otherInformation': otherInformation,

      // METADATA (timestamps properly serialized as Firestore Timestamp)
      'createdAt': Timestamp.fromDate(createdAt),

      // STATUS & TRACKING
      'status': status,
      'trackingNumber': '', // Will be generated by Cloud Function
      'adminNotes': adminNotes,

      // AFFILIATE INFO
      'affiliateId': affiliateId,
      'affiliateToken': null, // Will be updated by Cloud Function if provided
      'userId': userId,
      'guestEmail': guestEmail,
      'category': category,
    };
  }

  /// Create from Firestore document
  static SimpleShippingRequest fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data()!;

    // Helper to safely parse timestamps
    DateTime? parseTimestamp(dynamic value) {
      if (value == null) return null;
      if (value is Timestamp) return value.toDate();
      if (value is DateTime) return value;
      return null;
    }

    return SimpleShippingRequest(
      id: data['id'] ?? doc.id,
      affiliateId: data['affiliateId'],
      userId: data['userId'],
      guestEmail: data['guestEmail'] ?? data['clientEmail'] ?? '',
      freightType: () {
        final raw = (data['type'] as String?) ??
            (data['freightType'] as String?) ??
            'sea';
        if (raw == 'AIRPORT_TO_AIRPORT' || raw.toLowerCase() == 'air') {
          return 'air';
        }
        if (raw == 'DOOR_TO_DOOR' || raw.toLowerCase() == 'sea') return 'sea';
        return 'sea';
      }(),
      itemDescription: data['description'] ?? data['itemDescription'] ?? '',
      departingLocation: data['origin'] ?? data['departingLocation'] ?? '',
      destinationLocation:
          data['destination'] ?? data['destinationLocation'] ?? '',
      shipmentWeightKg:
          (data['weight'] ?? data['shipmentWeightKg'] ?? 0.0).toDouble(),
      shipmentDimensions: _reconstructDimensions(
        data['length'],
        data['width'],
        data['height'],
        data['shipmentDimensions'],
      ),
      shipmentPackaging:
          data['packagingType'] ?? data['shipmentPackaging'] ?? '',
      priority: () {
        final raw = (data['priority'] as String?) ?? 'regular';
        return raw == 'standard' ? 'regular' : raw;
      }(),
      senderName: data['clientName'] ?? data['senderName'] ?? '',
      senderAddress: data['senderAddress'] ?? '',
      senderPhone: data['clientPhone'] ?? data['senderPhone'] ?? '',
      senderEmail: data['senderEmail'] ?? '',
      receiverName: data['receiverName'] ?? '',
      receiverAddress: data['receiverAddress'] ?? '',
      receiverPhone: data['receiverPhone'] ?? '',
      receiverEmail: data['receiverEmail'] ?? '',
      attachmentUrls: List<String>.from(data['attachmentUrls'] ?? []),
      otherInformation: data['otherInformation'],
      createdAt: parseTimestamp(data['createdAt']) ?? DateTime.now(),
      status: data['status'] ?? 'pending',
      adminNotes: data['adminNotes'],
      category: (data['category'] as String?) ?? 'guest',
    );
  }

  /// Helper to reconstruct dimensions string from separate fields
  static String _reconstructDimensions(
    dynamic length,
    dynamic width,
    dynamic height,
    dynamic originalDimensions,
  ) {
    // If we have separate dimensions, reconstruct
    if (length != null && width != null && height != null) {
      return '${length}x${width}x$height';
    }
    // Otherwise use original if available
    if (originalDimensions != null && originalDimensions is String) {
      return originalDimensions;
    }
    return '0x0x0';
  }
}
