// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvOSiAdbWBqoQHFa0V-yLYKVU_AB_WZo',
    appId: '1:1056553474485:web:a1b2c3d4e5f6g7h8',
    messagingSenderId: '1056553474485',
    projectId: 'shopsnports',
    storageBucket: 'shopsnports.firebasestorage.app',
    authDomain: 'shopsnports.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLvOSiAdbWBqoQHFa0V-yLYKVU_AB_WZo',
    appId: '1:1056553474485:android:f8cf9c573a24361a4ea1fc',
    messagingSenderId: '1056553474485',
    projectId: 'shopsnports',
    storageBucket: 'shopsnports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXrotrbE2_1FYPDmhoPQ-jMzaoMFIiroY',
    appId: '1:1056553474485:ios:4009def792131b374ea1fc',
    messagingSenderId: '1056553474485',
    projectId: 'shopsnports',
    storageBucket: 'shopsnports.firebasestorage.app',
    androidClientId:
        '1056553474485-k482mjuem48a25vkbu0p1ds1q3fijtpj.apps.googleusercontent.com',
    iosClientId:
        '1056553474485-9elpnreelh3r1ihbfoejgld9plgjt2fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsnports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXrotrbE2_1FYPDmhoPQ-jMzaoMFIiroY',
    appId: '1:1056553474485:ios:4009def792131b374ea1fc',
    messagingSenderId: '1056553474485',
    projectId: 'shopsnports',
    storageBucket: 'shopsnports.firebasestorage.app',
    androidClientId:
        '1056553474485-k482mjuem48a25vkbu0p1ds1q3fijtpj.apps.googleusercontent.com',
    iosClientId:
        '1056553474485-9elpnreelh3r1ihbfoejgld9plgjt2fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsnports',
  );
}
